version: '2.0'
services:
  vote:
#    build:
#      context: .
#      dockerfile: .docker/Dockerfile
    image: 'uvs-vote'
    ports:
      - 8002:80
    volumes:
      - .:/var/www/html
      - /var/www/html/uvs-vote/.docker/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
